#!/bin/sh
root -l -q -b 'absDif_intV1_eta.C+(0)'
root -l -q -b 'absDif_intV1_eta.C+(1)'
root -l -q -b 'absDif_intV1_eta.C+(2)'
root -l -q -b 'absDif_intV1_eta.C+(3)'
root -l -q -b 'absDif_intV1_eta.C+(4)'
root -l -q -b 'absDif_intV1_eta.C+(5)'
root -l -q -b 'absDif_intV1_eta.C+(6)'
root -l -q -b 'absDif_intV1_eta.C+(7)'
root -l -q -b 'absDif_intV1_eta.C+(8)'
root -l -q -b 'absDif_intV1_eta.C+(9)'
root -l -q -b 'absDif_intV1_eta.C+(10)'
root -l -q -b 'absDif_intV1_eta.C+(11)'
root -l -q -b 'absDif_intV1_eta.C+(12)'
root -l -q -b 'absDif_intV1_eta.C+(13)'
root -l -q -b 'absDif_intV1_eta.C+(14)'
root -l -q -b 'absDif_intV1_eta.C+(15)'

root -l -q -b 'absDif_intV1_pt.C+(0)'
root -l -q -b 'absDif_intV1_pt.C+(1)'
root -l -q -b 'absDif_intV1_pt.C+(2)'
root -l -q -b 'absDif_intV1_pt.C+(3)'
root -l -q -b 'absDif_intV1_pt.C+(4)'
root -l -q -b 'absDif_intV1_pt.C+(5)'
root -l -q -b 'absDif_intV1_pt.C+(6)'
root -l -q -b 'absDif_intV1_pt.C+(7)'
root -l -q -b 'absDif_intV1_pt.C+(8)'
root -l -q -b 'absDif_intV1_pt.C+(9)'
root -l -q -b 'absDif_intV1_pt.C+(10)'
root -l -q -b 'absDif_intV1_pt.C+(11)'
root -l -q -b 'absDif_intV1_pt.C+(12)'
root -l -q -b 'absDif_intV1_pt.C+(13)'
root -l -q -b 'absDif_intV1_pt.C+(14)'
root -l -q -b 'absDif_intV1_pt.C+(15)'

rm *_C.so *.d *.pcm *~ \#*\#
